import { lazy } from 'react'

export const LandingPage = lazy(() => import('@/features/landing/pages/LandingPage'))
export const LoginPage = lazy(() => import('@/features/auth/pages/LoginPage'))
export const RegisterPage = lazy(() => import('@/features/auth/pages/RegisterPage'))
export const ForgotPasswordPage = lazy(() => import('@/features/auth/pages/ForgotPasswordPage'))
export const ResetPasswordPage = lazy(() => import('@/features/auth/pages/ResetPasswordPage'))
export const CheckEmailPage = lazy(() => import('@/features/auth/pages/CheckEmailPage'))
export const VerifyEmailPage = lazy(() => import('@/features/auth/pages/VerifyEmailPage'))
export const LegalPage = lazy(() => import('@/features/auth/pages/LegalPage'))
export const ForbiddenPage = lazy(() => import('@/features/auth/pages/ForbiddenPage'))
export const ProfilePage = lazy(() => import('@/features/profile/pages/ProfileDetailsPage'))
export const TeacherOverviewPage = lazy(() => import('@/features/classes/pages/TeacherOverviewPage'))
export const CreateClassPage = lazy(() => import('@/features/classes/pages/CreateClassPage'))
export const ClassStudentsPage = lazy(() => import('@/features/classes/pages/ClassStudentsPage'))
export const ClassSettingsPage = lazy(() => import('@/features/classes/pages/ClassSettingsPage'))
export const ClassJoinRequestsPage = lazy(() => import('@/features/classes/pages/ClassJoinRequestsPage'))
export const TeacherNotificationsPage = lazy(() => import('@/features/notifications/pages/TeacherNotificationsPage'))
export const TeacherTuitionPage = lazy(() => import('@/features/tuition/pages/TeacherTuitionPage'))
export const StudentClassesPage = lazy(() => import('@/features/enrollments/pages/StudentClassesPage'))
export const AdminUsersPage = lazy(() => import('@/features/administration/pages/AdminUsersPage'))
