import { CalendarOutlined, CheckCircleOutlined, ClockCircleOutlined, PlusOutlined, StarOutlined } from '@ant-design/icons'
import { Alert, Spin } from 'antd'
import { useSearchParams } from 'react-router-dom'
import { useStudentOverview } from '@/features/enrollments/hooks/useStudentOverview'
import '@/features/enrollments/enrollments.css'
import '@/features/enrollments/student-dashboard.css'

export default function StudentClassesPage() {
  const[params,setParams]=useSearchParams();const query=useStudentOverview(params.get('classId')||undefined)
  if(query.isLoading)return <div className="student-overview-state"><Spin size="large"/></div>
  if(query.isError)return <Alert type="error" showIcon message="Không thể tải tổng quan lớp học"/>
  const data=query.data;const classes=data?.classes??[];const overview=data?.overview;if(!overview)return <main className="student-classes-old"><header className="student-classes-old__head"><div><h1>Tổng quan <strong>lớp học</strong></h1><p>Theo dõi lớp học, lịch sắp tới và bài tập của bạn.</p></div><button className="student-classes-old__join" type="button"><PlusOutlined/> Tham gia lớp</button></header><section className="student-overview-empty"><div><h2>Bạn chưa tham gia lớp học nào</h2><p>Vui lòng tham gia lớp học để xem tổng quan lịch học, bài tập và tiến độ.</p></div></section></main>
  const metrics=[['Điểm học tập',overview.kpis?.grades,'green'],['Học phí',overview.kpis?.tuition,'amber'],['Hạn nộp bài',overview.kpis?.nextDueAssignment,'violet'],['Lịch học',overview.kpis?.nextSession,'blue'],['Tổng kết điểm danh',overview.kpis?.attendance,'rose']] as const
  return <main className="student-dashboard"><header><div><h1>Tổng quan lớp <select value={overview.classId} onChange={e=>setParams({classId:e.target.value})}>{classes.map(c=><option key={c.classId} value={c.classId}>{c.className}</option>)}</select></h1><p>Đây là nhịp học hôm nay với {overview.teacherDisplayName||'giáo viên'}.</p></div><div className="student-date"><CalendarOutlined/> {new Date().toLocaleDateString('vi-VN')}</div></header><section className="student-kpis">{metrics.map(([label,item,tone])=><article className={`tone-${tone}`} key={label}><span><StarOutlined/></span><em>{item?.meta||'Cập nhật'}</em><small>{label}</small><strong>{item?.available?item.value||'—':'—'}</strong><p>{item?.detail||'Chưa có dữ liệu'}</p></article>)}</section><section className="student-panels"><article><h2><CalendarOutlined/> Lịch sắp tới <em>Tuần này</em></h2>{overview.upcomingSchedule?.length?<ul>{overview.upcomingSchedule.map(x=><li key={x.id}><b>{x.date}</b><div><strong>{x.subject}</strong><small>{x.time} · {x.teacher||overview.teacherDisplayName}</small></div></li>)}</ul>:<p className="panel-empty">Chưa có lịch học sắp tới.</p>}</article><article><h2><CheckCircleOutlined/> Bài tập sắp nộp <em>{overview.upcomingAssignments?.length||0} việc</em></h2>{overview.upcomingAssignments?.length?<ul>{overview.upcomingAssignments.map(x=><li key={x.id}><ClockCircleOutlined/><div><strong>{x.label||x.title}</strong><small>{x.deadline||x.meta}</small></div></li>)}</ul>:<p className="panel-empty">Chưa có bài tập sắp nộp.</p>}</article><article><h2><StarOutlined/> Kế hoạch học tập <em>Cá nhân</em></h2><p className="panel-empty">Chưa có việc cần làm. Hãy thêm kế hoạch cho lớp này.</p></article></section></main>
}
